// import type { Metadata } from "next";
import { Inter, Bree_Serif, Young_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const breeSerif = Bree_Serif({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bree",
});
export const youngSerif = Young_Serif({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-young",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryClientProvider>
        <body className={`${inter.variable} ${youngSerif.variable} font-inter`}>
          <Navbar />
          {children}
        </body>
      </QueryClientProvider>
    </html>
  );
}
